#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

#foamCleanTutorials
#runApplication blockMesh
#restore0Dir
#- Run serial
#runApplication $(getApplication)

#- Run parallel
runApplication decomposePar -latestTime
runParallel $(getApplication)
#runApplication reconstructPar

#runApplication postChannel

#------------------------------------------------------------------------------
